### ISSUE TITLE
Is a hotfix merged back to develop?

### ISSUE THREAD

**Issue by EugenMayer** [datasift/gitflow#108]
Reading https://datasift.github.io/gitflow/GitFlowForGitHub.html under **9. Creating Hotfixes** i cannot find the information, if finishing a hotfix does actually merge back into master ( described ) but also in develop ( which is part of the usual gitflow and critical to the semantic of hotfix )

Could you clarify on that? Thank you

**Comment by stuartherbert** [comment]
Hi Eugen,

Yes, the code attempts to merge a completed hotfix back into the `develop` branch too.

Best regards,
Stu
