### ISSUE TITLE
OS X support

### ISSUE THREAD

**Issue by mbrace** [datasift/gitflow#39]
We were previously using gitflow, but with some modifications and plan on making more.  With our workflow including github, we'll be switching over to using hubflow shortly.  Our shop uses OS X for development machines pretty exclusively, so I'm going through and fixes issues I run across, so there will be a myriad of pull requests coming in focusing on cross-platform support.

**Comment by aehlke** [comment]
@mbrace how has this gone for you? Are you still using this on OS X, and have you been able to get any fixes merged in as needed?

**Comment by mbrace** [comment]
This has been working great for us.  There haven't been any additional changes needed for OS X support so I'm going to go ahead and close this out.
