### ISSUE TITLE
Is the project dead?

### ISSUE THREAD

**Issue by jeffreyscottgraham** [datasift/gitflow#96]
Dead or Alive is it?

**Comment by stuartherbert** [comment]
It's still alive. I haven't moved it forward because the latest tagged release has been doing everything I've needed.

Anything in particular prompting the question?

**Comment by jeffreyscottgraham** [comment]
The current concern is about this warning when when running "git hf update":     "warning: empty strings as pathspecs will be made invalid in upcoming releases. please use . instead if you meant to match all path"-----Original Message-----

**Comment by thewalkingtoast** [comment]
This affects me as well. `git 2.16+` doesn't work due to pathspec

**Comment by stuartherbert** [comment]
I'll see if I can get a fix for that out tonight.

**Comment by stuartherbert** [comment]
I've created a new branch `hotfix/1.5.3`. It contains a fix for the empty pathspec problem.

Could you test this please, and let me know if that solves the problem for you? Thanks in advance.

**Comment by thewalkingtoast** [comment]
It works great. Thank you very much for being quick and responsive. :) 👍

**Comment by stuartherbert** [comment]
Thank you for testing it so quickly. I'll get a tagged release out shortly.

**Comment by ladyrassilon** [comment]
@stuartherbert also tested and it fixed the problem I was having.

```bash
$ git hf release finish 0.1.9
Fetching origin
Fetching origin
fatal: empty string is not a valid pathspec. please use . instead if you meant to match all paths
Unable to checkout branch ''
```

Thanks for fixing this :)

**Comment by stuartherbert** [comment]
v1.5.3 has now been tagged and released.

Thank you everyone for reporting this, and making sure I got it done.

**Comment by thewalkingtoast** [comment]
Submitted to homebrew: https://github.com/Homebrew/homebrew-core/pull/23574
